name: Close inactive issues
on:
  schedule:
    - cron: "10 * * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "Acest issue a fost marcat automat ca STALE pentru ca timp de 30 de zile nu a avut activitate."
          close-issue-message: "Acest issue a fost inchis automat deoarce timp de 14 zile dupa ce a fost marcat ca STALE nu a avut activitate."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
